import { Category, Product, User } from "../types/pos.js";

export const mockUser: User = {
  id: "1",
  name: "John Doe",
  email: "john@example.com",
  role: "admin",
};

export const mockCategories: Category[] = [
  { id: "1", name: "Beverages" },
  { id: "2", name: "Snacks" },
  { id: "3", name: "Meals" },
  { id: "4", name: "Desserts" },
  { id: "5", name: "Hot Drinks" },
];

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Cola",
    categoryId: "1",
    itemCode: "ITEM-0001",
    hasVariants: true,
    lowStockThreshold: 10,
    status: "active",
    variants: [
      { id: "v1", productId: "1", name: "Small (330ml)", price: 1.5, stock: 50 },
      { id: "v2", productId: "1", name: "Medium (500ml)", price: 2.0, stock: 40 },
      { id: "v3", productId: "1", name: "Large (1L)", price: 3.0, stock: 30 },
    ],
  },
  {
    id: "2",
    name: "Orange Juice",
    categoryId: "1",
    itemCode: "ITEM-0002",
    hasVariants: false,
    price: 2.5,
    stock: 60,
    lowStockThreshold: 15,
    status: "active",
  },
  {
    id: "3",
    name: "Potato Chips",
    categoryId: "2",
    itemCode: "ITEM-0003",
    hasVariants: true,
    lowStockThreshold: 20,
    status: "active",
    variants: [
      { id: "v4", productId: "3", name: "Regular", price: 1.2, stock: 100 },
      { id: "v5", productId: "3", name: "BBQ", price: 1.2, stock: 80 },
      { id: "v6", productId: "3", name: "Sour Cream", price: 1.2, stock: 75 },
    ],
  },
  {
    id: "4",
    name: "Chocolate Bar",
    categoryId: "2",
    itemCode: "ITEM-0004",
    hasVariants: false,
    price: 1.8,
    stock: 120,
    lowStockThreshold: 30,
    status: "active",
  },
  {
    id: "5",
    name: "Burger Combo",
    categoryId: "3",
    itemCode: "ITEM-0005",
    hasVariants: true,
    lowStockThreshold: 5,
    status: "active",
    variants: [
      { id: "v7", productId: "5", name: "Classic Burger", price: 5.5, stock: 25 },
      { id: "v8", productId: "5", name: "Cheese Burger", price: 6.0, stock: 20 },
      { id: "v9", productId: "5", name: "Double Burger", price: 7.5, stock: 15 },
    ],
  },
  {
    id: "6",
    name: "Pizza Slice",
    categoryId: "3",
    itemCode: "ITEM-0006",
    hasVariants: false,
    price: 3.5,
    stock: 40,
    lowStockThreshold: 10,
    status: "active",
  },
  {
    id: "7",
    name: "Ice Cream",
    categoryId: "4",
    itemCode: "ITEM-0007",
    hasVariants: true,
    lowStockThreshold: 8,
    status: "active",
    variants: [
      { id: "v10", productId: "7", name: "Vanilla", price: 2.5, stock: 35 },
      { id: "v11", productId: "7", name: "Chocolate", price: 2.5, stock: 30 },
      { id: "v12", productId: "7", name: "Strawberry", price: 2.5, stock: 28 },
    ],
  },
  {
    id: "8",
    name: "Brownie",
    categoryId: "4",
    itemCode: "ITEM-0008",
    hasVariants: false,
    price: 2.0,
    stock: 45,
    lowStockThreshold: 12,
    status: "active",
  },
  {
    id: "9",
    name: "Coffee",
    categoryId: "5",
    itemCode: "ITEM-0009",
    hasVariants: true,
    lowStockThreshold: 10,
    status: "active",
    variants: [
      { id: "v13", productId: "9", name: "Espresso", price: 2.0, stock: 50 },
      { id: "v14", productId: "9", name: "Cappuccino", price: 3.0, stock: 45 },
      { id: "v15", productId: "9", name: "Latte", price: 3.5, stock: 40 },
    ],
  },
  {
    id: "10",
    name: "Hot Chocolate",
    categoryId: "5",
    itemCode: "ITEM-0010",
    hasVariants: false,
    price: 2.8,
    stock: 55,
    lowStockThreshold: 15,
    status: "active",
  },
];
